services:
  db:
    image: postgres:15-alpine
    container_name: deals_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-minhasenha}
      POSTGRES_DB: ${DB_NAME:-deals_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
